#include "monty.h"

/**
 * is_number - function that check if an string is a number
 * @s: the string to check
 *
 * Return: 1 is a number, 0 is not number
 */
int is_number(char *s)
{
	int index;

	for (index = 0; s[index] != '\0'; index++)
	{
		if (isdigit(s[index]) == 0)
			return (0);
	}
	return (1);
}
/**
 * print_stack - Function that prints all the elements of a stack_t list.
 * @h: The linked list for print.
 *
 * Return: The num of elements.
 */
size_t print_stack(stack_t *h)
{
	int num_elem = 0;

	if (h)
	{
		dprintf(STDOUT_FILENO, "%d\n", h->n);
		num_elem++;
		num_elem += print_stack(h->next);
	}
	return (num_elem);
}

/**
 * freezerr - Function that free all memory allocated
 * @file_p: is the file descriptor pointer to closed
 * @stack: the stack to be freezed
 * @line: input line file generated by getline
 * @status: the exit status
 */
void freezerr(FILE **file_p, stack_t **stack, char **line, int status)
{
	fclose(*file_p);
	if (*line) /* free memory of getline */
		free(*line), *line = NULL;
	free_stack(*stack);
	exit(status);
}


